spring.application.name=mvc

# Cambiar el puerto del servidor (por ejemplo, al 9090)
server.port=9090

# Modificar la cantidad maxima de hilos de Tomcat de 200 a 1000
server.tomcat.threads.max=1000

# Opcional: Hilos minimos que se quedan activos esperando peticiones
server.tomcat.threads.min-spare=10
